### ISSUE TITLE
Problema em mexer o robô no simulador

### ISSUE THREAD

**Issue by LuanaCamposA** [robocin/ssl-client#1]
Bom dia!
 Eu segui o passo-a-passo que está no Read-me, mas tive dificuldade em fazer o robô se mover no grSim, porque o final do passo-a-passo não deixa claro que é necessário executar o ./client, após ter seguido todos os passos. 
  Assim, após seguir todos os passos, a única coisa que foi possível fazer foi abrir o grSim.

**Comment by lhcavalcanti** [comment]
Oi @LuanaCamposA , se entendi o problema está sendo rodar o código do client. Então usamos o Qt Creator, adicionei um passo no tutorial antes de editar o código que é abrir o projeto no Qt. Com o projeto na IDE do Qt da para editar o código e rodar pelo botão de Run (Ctrl + R). 
Qualquer outra dúvida ou se não tiver ficado muito claro no readme só avisar, qualquer coisa passa no RC amanhã!
